name: attributed_text
description: Text with metadata spans for easy text editing and styling.
version: 0.2.2
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  characters: ^1.2.0
  collection: ^1.15.0
  logging: ^1.0.1
  meta: ^1.7.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.0.4
