name: super_editor_markdown
description: Markdown (de)serialization for super_editor documents.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  super_editor:
    git:
      url: https://github.com/simpleclub-extended/super_editor
      path: super_editor
      ref: simpleclub-stable
  logging: ^1.3.0
  markdown: ^7.2.1

dependency_overrides:
  # Override to local mono-repo path so devs can test this repo
  # against changes that they're making to other mono-repo packages
  super_editor:
    path: ../super_editor
  super_text_layout:
    path: ../super_text_layout
  attributed_text:
    path: ../attributed_text

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_test_robots: ^0.0.22
  flutter_test_runners: ^0.0.4
  golden_toolkit: ^0.15.0

flutter:
# no Flutter configuration
