name: super_editor_markdown
publish_to: "none"
description: Markdown (de)serialization for super_editor documents.
version: 0.1.7
homepage: https://github.com/superlistapp/super_editor
funding:
  - https://flutterbountyhunters.com
  - https://github.com/sponsors/matthew-carroll
topics:
  - rich-text-editor
  - editor
  - markdown
  - super-editor

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  super_editor:
    git:
      url: https://github.com/simpleclub-extended/super_editor
      path: super_editor
      ref: simpleclub-main
  logging: ^1.3.0
  markdown: ^7.2.1

dependency_overrides:
  super_editor:
    path: ../super_editor
  super_text_layout:
    path: ../super_text_layout
  attributed_text:
    path: ../attributed_text

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_test_robots: ^0.0.22
  flutter_test_runners: ^0.0.4
  golden_toolkit: ^0.15.0

  super_text_layout: ^0.1.12

flutter:
# no Flutter configuration
