name: website
description: The marketing website for SuperEditor.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  follow_the_leader: ^0.0.4+7
  overlord: ^0.0.3+5
  super_editor:
    git:
      url: https://github.com/simpleclub-extended/super_editor
      path: super_editor
      ref: simpleclub-stable
  super_text_layout:
    git:
      url: https://github.com/simpleclub-extended/super_editor
      path: super_text_layout
      ref: simpleclub-stable
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

dependency_overrides:
  # Override to local mono-repo path so devs can test this repo
  # against changes that they're making to other mono-repo packages
  attributed_text:
    path: ../attributed_text
  super_editor:
    path: ../super_editor
  super_text_layout:
    path: ../super_text_layout

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Regular.woff
        - asset: assets/fonts/Aeonik-Bold.woff
          weight: 700
        - asset: assets/fonts/Aeonik-Light.woff
          weight: 300
        - asset: assets/fonts/Aeonik-Thin.woff
          weight: 100
